# **A Deep Dive into range, arange, linspace & logspace**


In [ ]:
import numpy as np

- 1. **Range**

In [ ]:
r = range(10)
print(r)

r = range(0, 10, 2)
print(r)

r = range(10, 0, -2)
print(r)

print(6 in r)
print(list(r))

range(0, 10)
range(0, 10, 2)
range(10, 0, -2)
True
[10, 8, 6, 4, 2]


- 2. arange

In [ ]:
arr = np.arange(0, 10, 2)
print(arr)

arr = np.arange(10, 0, -2)
print(arr)

arr = np.arange(0, 10, .5)
print(arr)

arr = np.arange(10, 0, -.5)
print(arr)




[0 2 4 6 8]
[10  8  6  4  2]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5  1.   0.5]


- 3. Linspace

In [ ]:
l = np.linspace(0, 10, 5)
print(l)

l = np.arange(0, 16, 5)
print(l)

l = np.linspace(1, 10, 10)
print(l)

l = np.linspace(1, 10, 10, endpoint=False)
print(l)

l = np.linspace(1, 10, 10, retstep=True)
print(l)


[ 0.   2.5  5.   7.5 10. ]
[ 0  5 10 15]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]
(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), np.float64(1.0))


- 4. Logspace

In [ ]:
l = np.logspace(1, 10, 10)
print(l)

l = np.logspace(1, 10, 10, base=2)
print(l)

l = np.logspace(1, 10, 10, endpoint=False)
print(l)

l = np.logspace(1, 10, 10, base=2, endpoint=False)
print(l)

[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08 1.e+09 1.e+10]
[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
[1.00000000e+01 7.94328235e+01 6.30957344e+02 5.01187234e+03
 3.98107171e+04 3.16227766e+05 2.51188643e+06 1.99526231e+07
 1.58489319e+08 1.25892541e+09]
[  2.           3.73213197   6.96440451  12.99603834  24.25146506
  45.254834    84.44850629 157.58648491 294.06677888 548.74801282]


# **Array Manipulation Essentials : Reshaping, Flattening, Splitting**

In [1]:
import numpy as np

- 1. Flattening

In [2]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

print("---------------------------------------")

flat_arr = arr.flatten()
print(flat_arr)

[[1 2 3]
 [4 5 6]]
---------------------------------------
[1 2 3 4 5 6]


- 2. Reshape

In [5]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.shape)

print("---------------------------------------")

reshaped_arr = np.reshape(arr, (1,9))
print(reshaped_arr)
print(reshaped_arr.shape)

print("---------------------------------------")
print(reshaped_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
---------------------------------------
[[1 2 3 4 5 6 7 8 9]]
(1, 9)
---------------------------------------
[[1 2 3 4 5 6 7 8 9]]


- 3. Spilitting
  - Vsplit

In [8]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

print("---------------------------------------")

print(np.vsplit(arr, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------------------
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


  - - **hsplit**

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

print("---------------------------------------")

print(np.hsplit(arr, 3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------------------------------
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


- - split

In [15]:
arr = np.array([[1,2,3,4], [4,5,6,4], [7,8,9,4]])
print(arr)

print("---------------------------------------")

print(np.split(arr, 4, axis=1))

[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]
---------------------------------------
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]]), array([[4],
       [4],
       [4]])]


- 4. Merging

In [19]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,8,4,5])
arr3 = np.array([1,2,3,8,5])
arr4 = np.array([1,2,3,4,8])

concat_arr = np.concatenate((arr1, arr2, arr3, arr4))
print(concat_arr)

[1 2 3 4 5 1 2 8 4 5 1 2 3 8 5 1 2 3 4 8]


- - hstack

In [20]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,8,4,5])
arr3 = np.array([1,2,3,8,5])
arr4 = np.array([1,2,3,4,8])

concat_arr = np.hstack((arr1, arr2, arr3, arr4))
print(concat_arr)

[1 2 3 4 5 1 2 8 4 5 1 2 3 8 5 1 2 3 4 8]


- - **vstack**

In [21]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,8,4,5])
arr3 = np.array([1,2,3,8,5])
arr4 = np.array([1,2,3,4,8])

concat_arr = np.vstack((arr1, arr2, arr3, arr4))
print(concat_arr)

[[1 2 3 4 5]
 [1 2 8 4 5]
 [1 2 3 8 5]
 [1 2 3 4 8]]


- - **Stack**

In [23]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,8,4,5])
arr3 = np.array([1,2,3,8,5])
arr4 = np.array([1,2,3,4,8])

concat_arr = np.stack((arr1, arr2, arr3, arr4), axis = 1)
print(concat_arr)

[[1 1 1 1]
 [2 2 2 2]
 [3 8 3 3]
 [4 4 8 4]
 [5 5 5 8]]


In [24]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,8,4,5])
arr3 = np.array([1,2,3,8,5])
arr4 = np.array([1,2,3,4,8])

concat_arr = np.stack((arr1, arr2, arr3, arr4), axis = 0)
print(concat_arr)

[[1 2 3 4 5]
 [1 2 8 4 5]
 [1 2 3 8 5]
 [1 2 3 4 8]]


# **Advance Multidimensional Indexing**

In [25]:
import numpy as np

In [43]:
arr = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(arr)

print("-----------------------------------------")

print(arr[0])
print(arr[1])

print("-----------------------------------------")

print(arr[0][0])
print(arr[0][1])

print("-----------------------------------------")

print(arr[1][0])
print(arr[1][1])

print("-----------------------------------------")

print(arr[0][0][0])
print(arr[0][0][1])
print(arr[0][0][2])
print(arr[0][1][0])
print(arr[0][1][1])
print(arr[0][1][2])

print("-----------------------------------------")

print(arr[0][1][0])
print(arr[0][1][1])
print(arr[0][1][2])
print(arr[1][0][0])
print(arr[1][0][1])
print(arr[1][0][2])


print("--------------------------------------------")

#Access specific rows
print(arr[0])
print(arr[0:])
print(arr[0:, 0])
print(arr[0:, 1])
print(arr[0:, 0:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
-----------------------------------------
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
-----------------------------------------
[1 2 3]
[4 5 6]
-----------------------------------------
[7 8 9]
[10 11 12]
-----------------------------------------
1
2
3
4
5
6
-----------------------------------------
4
5
6
7
8
9
--------------------------------------------
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [7 8 9]]
[[ 4  5  6]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [45]:
arr = np.array([[[1,2,3],[4,5,6],[1,3,5]], [[7,8,9],[10,11,12],[4,5,3]], [[7,8,9],[10,11,12],[4,5,3]]])
print(arr)
print('-'*10)

# Access a specific Element
print(arr[0][1][2])
print(arr[0,1,2])
print('-'*10)

# Access a specific row
print(arr[0])
print(arr[0,:])
print(arr[0,:,:])
print(arr[:,0,:])
print(arr[:,:,0])
print('-'*10)

# Access with specific case
print(arr[[1,2], : , :])
print(arr[[1,2], : , 1])
print('-'*10)

# Access with specific conditions
print(arr[arr>5])

[[[ 1  2  3]
  [ 4  5  6]
  [ 1  3  5]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
----------
6
6
----------
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [4 5 6]
 [1 3 5]]
[[1 2 3]
 [7 8 9]
 [7 8 9]]
[[ 1  4  1]
 [ 7 10  4]
 [ 7 10  4]]
----------
[[[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]

 [[ 7  8  9]
  [10 11 12]
  [ 4  5  3]]]
[[ 8 11  5]
 [ 8 11  5]]
----------
[ 6  7  8  9 10 11 12  7  8  9 10 11 12]


# **Broadcasting for Efficient Calculations**

- 1. Arithmetic

In [1]:
import numpy as np

In [13]:
a = np.array([1,2,3])
b = np.array([[20, 30, 40],[40,50,60]])

print(a)
print(b)

print("----------------------------------------------")

#Addition with broadcasting
print(a+b)

print("----------------------------------------------")
print(a+5)

print("----------------------------------------------")
print(a)
print(a-b)

print("----------------------------------------------")
print(a * 2)
print(b * 2)

# Division
print(a / 2)
print(a / b)
print('---------'*10)

# Exponential
print(a ** 2)
print(a ** b)
print('---------'*10)

# Modulo
print(a % 2)
print(a % b)
print('---------'*10)


[1 2 3]
[[20 30 40]
 [40 50 60]]
----------------------------------------------
[[21 32 43]
 [41 52 63]]
----------------------------------------------
[6 7 8]
----------------------------------------------
[1 2 3]
[[-19 -28 -37]
 [-39 -48 -57]]
----------------------------------------------
[2 4 6]
[[ 40  60  80]
 [ 80 100 120]]
[0.5 1.  1.5]
[[0.05       0.06666667 0.075     ]
 [0.025      0.04       0.05      ]]
------------------------------------------------------------------------------------------
[1 4 9]
[[                   1           1073741824 -6289078614652622815]
 [                   1     1125899906842624 -3535985420588157519]]
------------------------------------------------------------------------------------------
[1 0 1]
[[1 2 3]
 [1 2 3]]
------------------------------------------------------------------------------------------


- 2. Comparison

In [14]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('----------'*10)

# >
print(a > b)
print('----------'*10)

# <
print(a < b)
print('----------'*10)

# >=
print(a >= b)
print('----------'*10)

# <=
print(a <= b)
print('----------'*10)

# ==
print(a == b)
print('----------'*10)

# !=
print(a != b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[False False False]
 [False False False]]
----------------------------------------------------------------------------------------------------
[[False False False]
 [ True  True  True]]
----------------------------------------------------------------------------------------------------
[[ True  True  True]
 [False False False]]
----------------------------------------------------------------------------------------------------
[[ True  True  True]
 [ True  True  True]]
----------------------------------------------------------------------------------------------------
[[ True  True  True]
 [False False False]]
----------------------------------------------------------------------------------------------------
[[False False False]
 [ True  True  True]]


- 3. Logical


In [15]:

a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])
print(a)
print(b)

print('----------'*10)

print(a & b)
print('----------'*10)

print(a | b)
print('----------'*10)

print(a ^ b)
print('-'*10)

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [0 0 2]]
----------------------------------------------------------------------------------------------------
[[1 2 3]
 [5 7 7]]
----------------------------------------------------------------------------------------------------
[[0 0 0]
 [5 7 5]]
----------


- 4. bitwise

In [16]:
a = np.array([1,2,3])
b = np.array([[1, 2, 3],[4,5,6]])

print(a)
print(b)
print('-'*10)

print(np.bitwise_and(a,b))

print(np.bitwise_or(a,b))

print(np.bitwise_xor(a,b))

print(np.bitwise_not(a,b))

print(np.right_shift(a,b))

print(np.left_shift(a,b))

[1 2 3]
[[1 2 3]
 [4 5 6]]
----------
[[1 2 3]
 [0 0 2]]
[[1 2 3]
 [5 7 7]]
[[0 0 0]
 [5 7 5]]
[[-2 -3 -4]
 [-2 -3 -4]]
[[0 0 0]
 [0 0 0]]
[[0 0 0]
 [0 0 0]]


# **Locating Elements with where**

- 1d array


In [23]:
np.random.seed(10)
arr = np.random.randint(1, 11, size = 10)
print(arr)
print(np.where(arr>5))

print('-'*10)
indices = np.where(arr >= 5)
print(list(indices[0]))
print('-'*10)

[10  5  1  2 10  1  2  9 10  1]
(array([0, 4, 7, 8]),)
----------
[np.int64(0), np.int64(1), np.int64(4), np.int64(7), np.int64(8)]
----------


- 2d Array

In [24]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3))

print(arr)
print('-'*10)

indices = np.where(arr >= 5)
print(indices)
print('-'*10)

print(arr[indices])

[[10  5  1]
 [ 2 10  1]
 [ 2  9 10]]
----------
(array([0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2]))
----------
[10  5 10  9 10]


- 3d Array

In [25]:
np.random.seed(10)
arr = np.random.randint(1,11,size = (3,3,3))

print(arr)
print('-'*10)

indices = np.where(arr >= 5)
print(indices)
print('-'*10)

print(arr[indices])

[[[10  5  1]
  [ 2 10  1]
  [ 2  9 10]]

 [[ 1  9  7]
  [ 5  4  1]
  [ 5  7  9]]

 [[ 2  9  5]
  [ 2  4  7]
  [ 6  4 10]]]
----------
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 0, 1, 2, 2, 0, 0, 1, 2, 2, 2, 0, 0, 1, 2, 2]), array([0, 1, 1, 1, 2, 1, 2, 0, 0, 1, 2, 1, 2, 2, 0, 2]))
----------
[10  5 10  9 10  9  7  5  5  7  9  9  5  7  6 10]
