# **Saving data in files**

In [ ]:
import numpy as np

- 1. Textfile

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

In [ ]:
np.savetxt('data.txt', arr, delimiter=',')

In [ ]:
'Ashish, Jangra, 25, Mentor, 29/10/1998'.split(',')

['Ashish', ' Jangra', ' 25', ' Mentor', ' 29/10/1998']

- 2. npy

In [ ]:
arr = np.array([[1,2,3], [4,5,6]])

In [ ]:
np.save('data.npy', arr)

- 3. Save the  data in csv

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

np.savetxt('data.csv',arr, delimiter = ',', header = 'a,b,c')

- 4.json file save  

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('data.json',arr, delimiter = ',', header = '{"data"  : [', footer = ']}')



- 5. yaml file save

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])

np.savetxt('data.yaml',arr, delimiter = ',', header = '- data : ')


# **Reading data from files**


- 1. textfile

In [ ]:
data = np.loadtxt('/content/data.txt', delimiter=',')

print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- 2. npy


In [ ]:
data = np.load('data.npy')

print(data)

[[1 2 3]
 [4 5 6]]


- 3. csv

In [ ]:
data = np.loadtxt('data.csv', delimiter=',', skiprows=1)

print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


- 4. json

In [ ]:
data = np.loadtxt('data.json', delimiter = ',')

print(data)


[[1. 2. 3.]
 [4. 5. 6.]]


- 5. yaml

In [ ]:
data = np.loadtxt('data.yaml', delimiter = ',')

print(data)

[[1. 2. 3.]
 [4. 5. 6.]]


# **Writing data in files**

In [ ]:
import numpy as np

- 1. Replaceing existing content

In [ ]:
data = np.array([1,2,3])
np.savetxt('data1.txt', data, delimiter=',')

data = np.array([3,4,5])
np.savetxt('data1.txt', data, delimiter=',')


In [ ]:
'Ritik', 25, 'Male'
'Asia', 24, 'Female'
'Ashish', 23, 'Male'
'Suresh', 62, 'Male'


- 2. Appending the data on existing file

In [ ]:
data = np.array([1,2,3])
np.savetxt('data2.txt', data, delimiter=',')

#data = np.array([3,4,5])
np.savetxt('data2.txt', data, delimiter=',', fmt='%d')

data

array([1, 2, 3])

In [ ]:
data = np.array([1,2,3])
np.savetxt('data3.txt', data, delimiter=',')