# **Arrays vs List**

In [1]:
import numpy as np

In [2]:
lst = [1,2,3]
print(lst)
print(type(lst))

[1, 2, 3]
<class 'list'>


In [3]:
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
print(lst == a)

[ True  True  True]


In [5]:
print(lst == a.tolist())

True


In [6]:
print(type(a))
print(type(a.tolist()))

<class 'numpy.ndarray'>
<class 'list'>


In [7]:
print(sorted(a) == sorted(lst))

True


- Adding element in an array vs list

In [8]:
lst = [1,2,3]
print(lst)
lst.append(4)
print(lst)
print('____')

arr = np.array([1,2,3])
print(arr)
arr = np.append(arr,4)
print(arr)

[1, 2, 3]
[1, 2, 3, 4]
____
[1 2 3]
[1 2 3 4]


- Removing elements in an array vs list

In [9]:
lst = [1,2,3]
print(lst)
lst.pop(2)
print(lst)
print('____')

arr = np.array([1,2,3])
print(arr)
arr = np.delete(arr,2)
print(arr)

[1, 2, 3]
[1, 2]
____
[1 2 3]
[1 2]


- Updating elements in an Arrays vs List

In [10]:
lst = [1, 2, 3]
print(lst)
lst[1] = 4
print(lst)
print("-------------------------------")
arr = np.array([1,2,3])
print(arr)
arr[2] = 6
print(arr)

[1, 2, 3]
[1, 4, 3]
-------------------------------
[1 2 3]
[1 2 6]


 * Comaparison in Array vs List

In [11]:
import time
import numpy as np

my_list = list(range(1000000))
my_array = np.arange(1000000)

#Search time for list

start_time = time.time()
for _ in range(100):
  if 500000 in my_list:
    pass
end_time = time.time()
print('List : ', end_time-start_time)

start_time = time.time()
for _ in range(100):
  if 500000 in my_array: # Changed search value to be within the array range
    pass
end_time = time.time()
print('Array : ', end_time - start_time)


print(len(my_list))
print(len(my_array))

List :  0.619441032409668
Array :  0.051717281341552734
1000000
1000000


In [12]:
time.time()

1754138595.5438275

In [13]:
my_array[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# **Converting Data Structures to Numpy Array**

- 1.1) Coveting a tuple to an array

In [14]:
tpl = (1,2,3)
print(tpl)
print(type(tpl))

print("---------------------------------------")

arr = np.array((tpl))
print(arr)
print(type(arr))

(1, 2, 3)
<class 'tuple'>
---------------------------------------
[1 2 3]
<class 'numpy.ndarray'>


- 1.2) Converting a list an array

In [15]:
lst = [1,2,3]
print(lst)
print(type(lst))

print("---------------------------------------")

arr = np.array((lst))
print(arr)
print(type(arr))

[1, 2, 3]
<class 'list'>
---------------------------------------
[1 2 3]
<class 'numpy.ndarray'>


- 1.3) Converting a dictionary to an array

In [16]:
dct = {1 : "apple", 2 : "Banana", 3 : "cherry"}
print(dct)
print(type(dct))

print("----------------------")

arr = np.array(dct)
print(arr)
print(type(arr))

print("----------------------")

arr_k = np.array(dct.keys())
arr_v = np.array(dct.values())
print(arr_k)
print(arr_v)

print("----------------------")

arr_k = np.array(list(dct.keys()))
arr_v = np.array(list(dct.values()))
print(arr_k)
print(arr_v)

print(type(arr_k))
print(type(arr_v))

{1: 'apple', 2: 'Banana', 3: 'cherry'}
<class 'dict'>
----------------------
{1: 'apple', 2: 'Banana', 3: 'cherry'}
<class 'numpy.ndarray'>
----------------------
dict_keys([1, 2, 3])
dict_values(['apple', 'Banana', 'cherry'])
----------------------
[1 2 3]
['apple' 'Banana' 'cherry']
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


- 1.4) Converting a set to an array


In [17]:
set_ = {1,2,3}
print(set_)
print(type(set_))

print("----------------------")

arr = np.array(set_)
print(arr)
print(type(arr))


{1, 2, 3}
<class 'set'>
----------------------
{1, 2, 3}
<class 'numpy.ndarray'>


- 1.5) Converting String to Array


In [18]:
arr = np.array('hello world')
print(arr)
print(type(arr))

hello world
<class 'numpy.ndarray'>


#  **Converting the Datatype of Numpy Array**


- 1.1) Create an array of integers

In [19]:
arr = np.array([1,2,3,4,5])
print(arr)


print("----------------------")

arr_ = arr.astype('float')
print(arr_)


print("----------------------")

arr_ = arr.astype('str')
print(arr_)


print("----------------------")

arr_ = arr.astype('bool')
print(arr_)



[1 2 3 4 5]
----------------------
[1. 2. 3. 4. 5.]
----------------------
['1' '2' '3' '4' '5']
----------------------
[ True  True  True  True  True]


- 1.2) Create an array of floats

In [20]:
arr = np.array([1.,2.,3.,4.,5.])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

[1. 2. 3. 4. 5.]
[1 2 3 4 5]
['1.0' '2.0' '3.0' '4.0' '5.0']
[ True  True  True  True  True]


- 1.3) Create an array of strings

In [21]:
arr = np.array(['1','2','3','4','5'])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('bool')
print(arr_)

['1' '2' '3' '4' '5']
[1 2 3 4 5]
[1. 2. 3. 4. 5.]
[ True  True  True  True  True]


- 1.4) Create an array of boolean

In [22]:
arr = np.array([True, False, False, False, True])
print(arr)

arr_ = arr.astype('int')
print(arr_)

arr_ = arr.astype('float')
print(arr_)

arr_ = arr.astype('str')
print(arr_)

[ True False False False  True]
[1 0 0 0 1]
[1. 0. 0. 0. 1.]
['True' 'False' 'False' 'False' 'True']


# **Creating Multi-dimensional Arrays**

- Create a 2D array from a list of lists

In [23]:
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


- Create a 3D array from a list of lists

In [24]:
arr = np.array([[[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]],
                [[1,2,3], [4,5,6], [7,8,9]]])
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


- Create a 2D array from a list of tuples

In [25]:
arr = np.array([(1,2,3), (4,5,6)])
print(arr)

[[1 2 3]
 [4 5 6]]


- Create a 2D array from a list of arrays

In [26]:
arr = np.array([np.array([1,2,3]), np.array([4,5,6])])
print(arr)

[[1 2 3]
 [4 5 6]]


- Create a 2D array from a list of strings

In [27]:
arr = np.array([['1','2','3'],['4','5','6']])
print(arr)

[['1' '2' '3']
 ['4' '5' '6']]


- Create a 2D array from a list of dictionaries

In [28]:
arr = np.array([{'a' : 1, 'b' : 2, 'c' : 3},{'d' : 4, 'e' : 5, 'f' : 6}])
print(arr)

[{'a': 1, 'b': 2, 'c': 3} {'d': 4, 'e': 5, 'f': 6}]


# **Finding details of an arrays**

- Print the shape of the array

In [29]:
arr = np.array([[1,1],[4,1],[2,3]])

print(arr.shape)

(3, 2)


- Print the number of dimensions of the array


In [30]:
arr = np.array([[1,1],[4,1],[2,3]])

print(arr.ndim)

2


- Print the data type of the array

In [31]:
arr = np.array([[1,1],[4,1],[2,3]])
print(arr.dtype)

int64


- Print the size of the array

In [32]:
arr = np.array([[1,1,2,2],[2,3,2,1]])
print(arr.size)

8


- Print the item size | bytes taken by each element in an array

In [33]:
arr = np.array([[1,1,2],[1,2,3],[3,2,1]])
print(arr.itemsize)

8


- Print the type of the array

In [34]:
print(type(arr))

<class 'numpy.ndarray'>


# **Working with Copy Function**

- **1. Copy function with lists**

In [42]:
lst = [1,2,3,4,5]
print(lst)
lst1 = lst
print(lst1)

print("-----------------------------------------")

lst[0] = 5
print(lst)
print(lst1)

print("-----------------------------------------")

lst1[4] = 6
print(lst)
print(lst1)

print()
print("---------------------------------------------")
print()

lst = [1,2,3,4,5]
print(lst)
lst1 = lst.copy()
print(lst1)

print("-----------------------------------------")

lst[0] = 5
print(lst)
print(lst1)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
-----------------------------------------
[5, 2, 3, 4, 5]
[5, 2, 3, 4, 5]
-----------------------------------------
[5, 2, 3, 4, 6]
[5, 2, 3, 4, 6]

---------------------------------------------

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
-----------------------------------------
[5, 2, 3, 4, 5]
[1, 2, 3, 4, 5]


- **2. Copy function with arrays**

In [45]:
arr = np.array([1,2,3,4,5])
arr_ = arr.copy()
print(arr)
print(arr_)

print("-----------------------------------------")

arr[0] = 5
print(arr)
print(arr_)
arr[0] = 1

print("-----------------------------------------")

arr_[0] = 5
print(arr)
print(arr_)

[1 2 3 4 5]
[1 2 3 4 5]
-----------------------------------------
[5 2 3 4 5]
[1 2 3 4 5]
-----------------------------------------
[1 2 3 4 5]
[5 2 3 4 5]


# **Exploring Indexing and Slicing in NumPy**

- **1. Indexing & Slicing in Lists**


In [75]:
lst = [1,2,3,4,5,6,7,8,9]
print(lst[2])
print("------------------------------------------")
print(lst[-1])
print("------------------------------------------")


print(lst[0],lst[1])
print("------------------------------------------")

print(lst[0:2])
print("------------------------------------------")

print(lst[1:10])
print("------------------------------------------")

print(lst[:])
print("------------------------------------------")


print(lst[1:6])
print("------------------------------------------")

print(lst[1:-1])


3
------------------------------------------
9
------------------------------------------
1 2
------------------------------------------
[1, 2]
------------------------------------------
[2, 3, 4, 5, 6, 7, 8, 9]
------------------------------------------
[1, 2, 3, 4, 5, 6, 7, 8, 9]
------------------------------------------
[2, 3, 4, 5, 6]
------------------------------------------
[2, 3, 4, 5, 6, 7, 8]


In [74]:
print(lst[::])
print("------------------------------------------")

print(lst[::3])
print("------------------------------------------")

print(lst[1:-1:2])
print("------------------------------------------")

print(lst[::-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9]
------------------------------------------
[1, 4, 7]
------------------------------------------
[2, 4, 6, 8]
------------------------------------------
[9, 8, 7, 6, 5, 4, 3, 2, 1]


- 2. Indexing and Slicing in Arrays

In [76]:
my_array = np.array([1, 2, 3, 4, 5])

print(my_array[0])
print("------------------------------------------")

print(my_array[-1])
print("------------------------------------------")

print(my_array[2])
print("------------------------------------------")


print(my_array[1:4])
print("------------------------------------------")

print(my_array[:3])
print("------------------------------------------")

print(my_array[3:])
print("------------------------------------------")

print(my_array[::2])
print("------------------------------------------")

print(my_array[::-1])
print("------------------------------------------")


my_array[0] = 10
print("------------------------------------------")

print(my_array)
print("------------------------------------------")


np.delete(my_array, 1)
print("------------------------------------------")

print(my_array)
print("------------------------------------------")


np.insert(my_array, 1, [20, 30])
print("------------------------------------------")

print(my_array)
print("------------------------------------------")


1
------------------------------------------
5
------------------------------------------
3
------------------------------------------
[2 3 4]
------------------------------------------
[1 2 3]
------------------------------------------
[4 5]
------------------------------------------
[1 3 5]
------------------------------------------
[5 4 3 2 1]
------------------------------------------
------------------------------------------
[10  2  3  4  5]
------------------------------------------
------------------------------------------
[10  2  3  4  5]
------------------------------------------
------------------------------------------
[10  2  3  4  5]
------------------------------------------


# **Creating fixed size Arrays**

- 1. Zeros

In [78]:
zeros_array = np.zeros(10)
print(zeros_array)
print('-----------------------------')

zeros_array = np.zeros((2, 4))
print(zeros_array)
print('-----------------------------')

zeros_array = np.zeros((2, 3, 4))
print(zeros_array)
print('-----------------------------')

zeros_array = np.zeros((2, 3), dtype = int)
print(zeros_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
-----------------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
-----------------------------
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
-----------------------------
[[0 0 0]
 [0 0 0]]


- 2. Ones

In [79]:
ones_array = np.ones(10)
print(ones_array)
print('-----------------------------')

ones_array = np.ones((2, 4))
print(ones_array)
print('-----------------------------')

ones_array = np.ones((2, 3, 4))
print(ones_array)
print('-----------------------------')

ones_array = np.ones((2, 3), dtype = int)
print(ones_array)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
-----------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
-----------------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
-----------------------------
[[1 1 1]
 [1 1 1]]


- 3. Eye

In [80]:
eye_array = np.eye(3)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4)
print(eye_array)
print('-----')

eye_array = np.eye(3, 4, dtype = int)
print(eye_array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
-----
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


- 4. Random Number Generation

In [81]:
print(np.random.rand())
print(np.random.rand(10))
print(np.random.rand(3, 3))

print(np.random.randint(100))
print(np.random.randint(100, size=10))
print(np.random.randint(100, size=(3, 3)))
print(np.random.randint(low=100, high=200, size=(3, 3)))

# Generate a random number from a normal distribution with mean 0 and standard deviation 1
print(np.random.randn())

# Generate a 2D array of 3x3 random numbers from a uniform distribution between 0 and 1
print(np.random.uniform(size=(3, 3)))

# Generate a 2D array of 3x3 random numbers from a binomial distribution with n=10 and p=0.5
print(np.random.binomial(10, 0.5, size=(3, 3)))

# Poisson ,Exponential, Gamma, Chi-squared, T-distribution, F-distribution Beta Log-normal Laplace


0.7568957003195118
[0.61921192 0.95729911 0.1070616  0.75394349 0.85602769 0.85431154
 0.20797056 0.10369283 0.5483784  0.91533233]
[[0.21576698 0.16256359 0.77364679]
 [0.87726577 0.58975165 0.31634827]
 [0.46849978 0.80905347 0.11430593]]
84
[86 96 19 58 95 31 75  9 26 39]
[[55 43 12]
 [46  2  8]
 [ 5 56 71]]
[[128 153 184]
 [107 169 196]
 [182 160 190]]
-0.29098235607761375
[[0.11868977 0.290976   0.54103604]
 [0.81140288 0.33662094 0.22791331]
 [0.28227055 0.52281237 0.31506559]]
[[6 4 3]
 [4 5 6]
 [7 6 4]]


In [83]:
arr = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,3,3,4,5])
for i in range(len(arr)):
  print(i, ":", arr.tolist().count(i))

0 : 0
1 : 2
2 : 2
3 : 4
4 : 3
5 : 3
6 : 1
7 : 1
8 : 1
9 : 1
10 : 0
11 : 0
12 : 0
13 : 0
14 : 0
15 : 0
16 : 0
17 : 0


In [85]:
for i in range(1,10):
  print(i, " : ", arr.tolist().count(i))

1  :  2
2  :  2
3  :  4
4  :  3
5  :  3
6  :  1
7  :  1
8  :  1
9  :  1


In [87]:
arr = np.random.randint(low = 1, high = 100, size = (1000))
arr

array([56, 71, 96, 96, 76, 87, 88, 29, 46, 40, 60, 48, 37, 26, 74, 40, 87,
       60, 67, 17, 29, 91, 12, 22, 16, 82, 75, 59,  7, 81,  2, 50, 54,  4,
        2, 50, 99, 46, 50, 62, 73, 23, 74, 70, 63, 26, 90, 62, 73, 47, 35,
       72, 97, 91, 57, 94, 28, 85, 61, 63, 92, 58, 62, 39, 27, 40, 37, 19,
       73, 97, 19, 19, 83, 98, 79, 85,  8, 11, 55,  2, 49,  5,  3, 46, 79,
       84, 33, 26, 88, 16, 28, 66, 93, 29, 65, 94, 41, 52, 87, 33, 28, 80,
       77, 22, 61, 14,  2,  1, 97, 56, 68, 96, 67, 22, 93, 40, 63, 92, 70,
        6, 96,  3, 23, 33, 23, 58,  1, 84, 43, 25, 46, 26, 66, 10, 28, 24,
       89, 71, 22, 26, 81, 84,  8, 82, 94, 41, 52, 18, 94, 85, 62, 17,  7,
       30, 94, 13, 80, 36, 58, 84, 55, 10, 88, 52, 57, 72, 69, 77, 96, 29,
       61, 44, 67, 61, 52, 68, 67, 77, 70, 99, 52, 18, 12, 27, 19, 53,  7,
       45,  8, 40, 44, 13, 24,  8, 31, 41, 14, 10, 67, 88, 61, 98, 15,  3,
       16, 71, 46, 65, 70, 14, 60, 20, 20, 41, 78, 61, 90, 14, 66,  6, 90,
       56, 53, 53, 61, 32

In [91]:
for i in range(len(arr)):
  count = arr.tolist().count(i)
  if count > 0:
    print(i, " : ", count)

1  :  9
2  :  10
3  :  12
4  :  7
5  :  9
6  :  6
7  :  10
8  :  8
9  :  9
10  :  12
11  :  13
12  :  6
13  :  9
14  :  18
15  :  9
16  :  12
17  :  14
18  :  9
19  :  8
20  :  7
21  :  13
22  :  14
23  :  7
24  :  12
25  :  9
26  :  16
27  :  9
28  :  12
29  :  13
30  :  11
31  :  10
32  :  6
33  :  9
34  :  11
35  :  5
36  :  7
37  :  17
38  :  13
39  :  9
40  :  16
41  :  10
42  :  9
43  :  9
44  :  8
45  :  11
46  :  16
47  :  7
48  :  6
49  :  8
50  :  10
51  :  5
52  :  14
53  :  14
54  :  13
55  :  9
56  :  11
57  :  9
58  :  14
59  :  9
60  :  16
61  :  12
62  :  10
63  :  14
64  :  7
65  :  5
66  :  12
67  :  16
68  :  11
69  :  6
70  :  15
71  :  16
72  :  10
73  :  10
74  :  6
75  :  9
76  :  6
77  :  8
78  :  9
79  :  6
80  :  11
81  :  7
82  :  10
83  :  9
84  :  8
85  :  8
86  :  11
87  :  12
88  :  9
89  :  7
90  :  11
91  :  9
92  :  5
93  :  9
94  :  12
95  :  5
96  :  15
97  :  11
98  :  10
99  :  9


# **Managing randomness with Seed**

- 1. Generating Random Numbers

In [94]:
import numpy as np

In [98]:
print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10, size = (3,3)))

0.383558063149946
[0.47274923 0.59134723 0.87176745]
[[2 2 9]
 [3 0 8]
 [2 3 8]]


- 2. Random Numbers with Seed


In [102]:
np.random.seed(2)

print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10, size = (3,3)))



0.43599490214200376
[0.02592623 0.54966248 0.43532239]
[[8 7 2]
 [1 5 4]
 [4 5 7]]


In [103]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10, size = (3,3)))



0.22199317108973948
[0.87073231 0.20671916 0.91861091]
[[8 4 7]
 [0 0 7]
 [1 5 7]]


In [104]:
np.random.seed(5)

print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10, size = (3,3)))



0.22199317108973948
[0.87073231 0.20671916 0.91861091]
[[8 4 7]
 [0 0 7]
 [1 5 7]]


In [106]:
np.random.seed()

print(np.random.rand())
print(np.random.rand(3))
print(np.random.randint(10, size = (3,3)))



0.5627163859025782
[0.93792055 0.31121087 0.32833671]
[[5 6 5]
 [9 2 1]
 [8 0 0]]


In [107]:
np.random.rand(100)

array([0.31172021, 0.07861016, 0.67397899, 0.14889335, 0.9338315 ,
       0.74919655, 0.06059437, 0.89026981, 0.54068133, 0.41007339,
       0.19232779, 0.05009493, 0.06126595, 0.65989117, 0.42009965,
       0.14966537, 0.69937117, 0.99017248, 0.43298937, 0.17652957,
       0.0864215 , 0.11953123, 0.59599965, 0.54343401, 0.83155829,
       0.20641149, 0.31224207, 0.89626862, 0.00607878, 0.65805225,
       0.80376128, 0.30139209, 0.29100525, 0.00228589, 0.82469842,
       0.69431435, 0.22740038, 0.28576299, 0.84493675, 0.41186029,
       0.7539789 , 0.00829774, 0.29534941, 0.4711231 , 0.30102797,
       0.75359583, 0.21036185, 0.73775101, 0.82490915, 0.94157327,
       0.17186599, 0.88640346, 0.25297635, 0.86717488, 0.68066407,
       0.23674416, 0.11716783, 0.47491841, 0.08183719, 0.92937644,
       0.49461339, 0.32989392, 0.42432527, 0.07126765, 0.75646081,
       0.38644916, 0.653823  , 0.46964027, 0.53801251, 0.27034114,
       0.08675673, 0.09879769, 0.6353965 , 0.4331258 , 0.20565

In [108]:
np.random.randint(low =1, high = 100, size=100)

array([35, 68, 47, 39, 75, 91, 45, 11, 41, 55,  4, 52,  5, 98, 25, 90, 43,
        1, 39, 18, 26, 28, 76, 42, 32, 35, 15,  4, 10, 23, 56, 65, 92, 90,
       51, 87,  1, 31, 56, 27,  2, 48, 45, 39, 83, 73, 45, 86, 85, 21, 63,
       47, 32, 40, 37, 83,  2, 87, 83, 69,  4, 57, 30, 96, 80, 46, 20, 19,
       78, 27, 14, 48, 81, 82, 32, 62, 12, 37, 73,  4, 62, 79, 75, 35, 13,
       63, 60, 75, 45, 69, 27, 14, 29, 48, 23, 75, 21, 79, 83, 66])

In [111]:
np.random.seed(10)

for i in range(10):
  arr = np.random.randint(2, size = 1000)
  print(len(arr[arr==1]), len(arr[arr==0]))

481 519
504 496
494 506
533 467
501 499
504 496
527 473
499 501
508 492
504 496
