# **Dot Product and Matrix multiplication**

In [ ]:
import numpy as np

- 1. Dot product


In [ ]:
a = np.array([1,2])
b = np.array([2,3])

dot_product = np.dot(a,b)
print(dot_product)

8


In [ ]:
a = np.array([1,2,3])
b = np.array([2,3,4])

dot_product = np.dot(a,b)
print(dot_product)

20


In [ ]:
a = np.array([1,2])
b = np.array([5,3])

dot_product = np.dot(a,b)
print(dot_product)

11


- 2. Matrix Multiplication

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[2,3],[4,5]])
c = np.array([1,2])

mat1 = np.matmul(a,b)
mat2 = np.matmul(b,a)
mat3 = np.matmul(a,c)

print(mat1)
print(mat2)
print(mat3)


[[10 13]
 [22 29]]
[[11 16]
 [19 28]]
[ 5 11]


# **Determinant, Inverse and Transpose**


- 1. Determinant


In [ ]:
a = np.array([[1,2],[3,4]])
det = np.linalg.det(a)
print(f'{det:.2f}')

-2.00


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
det = np.linalg.det(a)
print(f'{det:.2f}')

0.00


- 2. Transpose

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
trans = np.transpose(a)
print(trans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
C = np.array([[1,2,3],[4,5,6]])
Transpose = np.transpose(C)
Transpose


array([[1, 4],
       [2, 5],
       [3, 6]])

- 3. Inverse

In [ ]:
A = np.array([[1,2],[3,4]])
Inverse = np.linalg.inv(A)
Inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# **System of Linear Equation**

- **1**. Linear Equation


In [ ]:
A = np.array([[1,2],[3,4]])
B= np.array([[5],[6]])
solution = np.linalg.solve(A,B)
solution


array([[-4. ],
       [ 4.5]])

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])
B = np.array([[10],[11],[12]])
solution = np.linalg.solve(A,B)
solution


array([[-9.33333333e+00],
       [ 9.66666667e+00],
       [ 3.55271368e-15]])

# **Eigen value and Eigen vector**

- 1. Eigen Vector & Eigen Values


In [ ]:
A = np.array([[5,4],[1,2]])

eigenvalues, eigenvectors = np.linalg.eig(A)
eigenvalues, eigenvectors


(array([6., 1.]),
 array([[ 0.9701425 , -0.70710678],
        [ 0.24253563,  0.70710678]]))